## 4.7 Continuous Integration per il modello ML ##
name: covid-cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python myTraining.py

          echo "## Model score" > report.md
          cat results/score_monitoring.txt >> report.md

          echo "## Data visual" >> report.md
          cml-publish results/report_threshold.png --md >> report.md
                    
          cml-send-comment report.md

          
