name: covid-cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python myTraining.py

          echo "## Model metrics" > report.md
          cat score.txt >> report.md

          echo "## Data visual" >> report.md
          cml-publish report.png --md >> report.md
          
          cml-send-comment report.md

          
