name: prediction-test
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml-run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Run Test
          pip install -r requirements.txt
          python test/test_model.py

          # Report the difference
          echo "## Experiment vs. Main
                Predizione fatta sui seguenti sintomi = breathing problem, fever, dry cough, heart disease, hyper tension, fatigue." > report.md
          git fetch --prune
          dvc metrics diff main --targets test/test_score_and_prediction.json --show-md >> report.md

          cml-send-comment report.md
          
          
